### ISSUE TITLE
bug: this repo exists

### ISSUE THREAD

**Issue by kakenbutter** [ericshu6/hehehehehehehe.github.io#1]
## Describe the issue
This repo exists. This completely unnecessary, as there is no content within it. As a friend of the creator/maintainer, I know that they do not plan on adding anything at all in the future.

## How to fix
Delete this repo immediately.

**Comment by ericshu6** [comment]
Oh-ho-ho-ho
Oh-ho-ho-ho
Oh-ho-ho-ho
Oh-ho-ho-ho
Everybody was kung fu fighting
Those cats were fast as lightning
In fact, it was a little bit frightening
But they fought with expert timing
There were funky China men from funky Chinatown
They were chopping them up, they were chopping them down
It's an ancient Chinese art and everybody knew their part
From a feint into a slip and a kicking from the hip
Everybody was kung fu fighting
Those cats were fast as lightning
In fact, it was a little bit frightening
But they fought with expert timing
There was funky Billy Chin and little Sammy Chung
He said, "Here comes the big boss (huh-ha!), let's get it on"
We took a bow and made a stand, started swaying with the hand
A sudden motion made me skip, now we're into a brand-new trip
Everybody was kung fu fighting
Those cats were fast as lightning
In fact, it was a little bit frightening
But they fought with expert timing
Oh-ho-ho-ho
Oh-ho-ho-ho
Oh-ho-ho-ho
Oh-ho-ho-ho
Everybody was kung fu fighting
Those cats were fast as lightning
In fact, it was a little bit frightening
But they fought with expert timing
Everybody was kung fu fighting
Those cats were fast as lightning
In fact, it was a little bit frightening
But they fought with expert timing
Kung fu fighting
Fast as lightning
Kung fu fighting
Fast as lightning
Kung fu fighting (keep on, keep on, keep on)
Fast as lightning
Kung fu fighting (everybody was kung fu fighting)
Fast as lightning

**Comment by kakenbutter** [comment]
Very funny. I guess I'll just close this issue.

**Comment by ericshu6** [comment]
yeah that's right u pankake!!!!!!!!!!!!!!!!!!!!!!!!
